// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjdtBewTrkZ5_sym9UOnGgMfroWWCBkA8',
    appId: '1:218781118030:web:bdb1defa77c6ae6c235d1f',
    messagingSenderId: '218781118030',
    projectId: 'kata-814e8',
    authDomain: 'kata-814e8.firebaseapp.com',
    storageBucket: 'kata-814e8.appspot.com',
    measurementId: 'G-1ZHT6HFVJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA42oXO8MzXoEUh8wE03ko4RMSysMzpryM',
    appId: '1:218781118030:android:324e714cf2358204235d1f',
    messagingSenderId: '218781118030',
    projectId: 'kata-814e8',
    storageBucket: 'kata-814e8.appspot.com',
  );

}